export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES'
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS'
export const FETCH_EMPLOYEES_FAILED = 'FETCH_EMPLOYEES_FAILED'
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
